# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('otd', models.CharField(max_length=30)),
                ('fio', models.CharField(max_length=50)),
                ('status', models.CharField(default='В стадии выполнения', max_length=20)),
                ('ispolnitel', models.CharField(max_length=30)),
                ('date_pub', models.DateTimeField(blank=True, null=True)),
                ('date_comp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
