# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generalapp', '0002_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='otd',
            field=models.CharField(max_length=100),
        ),
    ]
